### ISSUE TITLE
Binary download for Windows: rename to add ".exe" to filename.

### ISSUE THREAD

**Issue by sharpe5** [pacman82/odbc2parquet#126]
Thanks for such an amazing repo, everything just worked first time which is the mark of nicely written code. Much appreciated.

Very small issue: I downloaded the WIndows binaries here:
https://github.com/pacman82/odbc2parquet/releases/tag/v0.6.16

However, I had to manually edit the filename to add ".exe", and then it worked.

**Comment by pacman82** [comment]
Hello @sharpe5,

thanks for your nice feedback. You are welcome. I am a bit worried what an `.exe` file ending will do with regards to security settings then downloading the file, but I think just naming it `odbc2parquet.exe` and zipping it before publishing might do the trick.

Cheers, Markus

**Comment by sharpe5** [comment]
I considered security settings as well, I figured that was the reason
behind it. I think a .zip file is the best, as it's not immediately
executable with a click. BTW, this is probably the easiest-to-use SQL
utility I've ever come across, and it's perfect for exporting data to
Python for in-depth analysis. Thanks again!

**Comment by pacman82** [comment]
Thanks again for your kind words.

FYI: If it is Data Analysis in Python you want to do, I may have a treat for you. It is still young, but minmal viable product is there:

https://github.com/pacman82/arrow-odbc-py
