### ISSUE TITLE
Attempting to list drivers using odbc2parquet  0.6.2.7 on Oracle Linux 7.8 after compiling it on the same os fails with State: S1009, Native error: 0, Message: [unixODBC][Driver Manager]Invalid attribute value

### ISSUE THREAD

**Issue by chrisfw** [pacman82/odbc2parquet#168]
[svrvdef@tmwenqtrn utils]$ ./odbc2parquet
odbc2parquet 0.6.27
Query an ODBC data source at store the result in a Parquet file

USAGE:
    odbc2parquet [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -q, --quiet      Only print errors to standard error stream. Supresses warnings and all other
                     log levels independent of the verbose mode
    -v, --verbose    Verbose mode (-v, -vv, -vvv, etc)
    -V, --version    Print version information

SUBCOMMANDS:
    completions          Generate shell completions
    help                 Print this message or the help of the given subcommand(s)
    insert               Read the content of a parquet and insert it into a table
    list-data-sources    List preconfigured data sources. Useful to find data source name to
                             connect to database
    list-drivers         List available drivers and their attributes
    query                Query a data source and write the result as parquet
[svrvdef@tmwenqtrn utils]$ ./odbc2parquet list-drivers
2022-03-24T16:18:54-07:00 - WARN - State: S1009, Native error: 0, Message: [unixODBC][Driver Manager]Invalid attribute value
Error: ODBC emitted an error calling 'SQLSetEnvAttr':
**State: S1009, Native error: 0, Message: [unixODBC][Driver Manager]Invalid attribute value**

**Comment by pacman82** [comment]
What version of Unix odbc is installed?

**Comment by pacman82** [comment]
Just released `odbc2parquet 0.6.28` which is going to emit a better error message in your situation. Still curious on what version of unixODBC you are running though.

Cheers, Markus

**Comment by chrisfw** [comment]
Hi Markus,

We are on unixODBC 2.3.1.

$ isql --version
unixODBC 2.3.1

Thanks,
Chris

**Comment by pacman82** [comment]
Hi Chris,

would you mind upgrading to a newer version, and tell me how it goes. FYI: In case your package manager does not provide the newest version, building unixODBC from source is pretty straight forward:

```
1. copy the unixODBC-2.3.9.tar.gz file somewhere you can create files and directories
2. gunzip unixODBC*.tar.gz
3. tar xvf unixODBC*.tar
4. `./configure`
5. `make`
6. `make install`
```

I am not sure, at what version unixODBC officially supports `ODBC 3.80`, but the latest version does for sure. So updating it is something I find worth trying.

Cheers, Markus

**Comment by chrisfw** [comment]
Hi Markus,

I’ll need to find a server to test on as I was working on a customer vm, but I’ll do as you suggest and let you know what I find out.  Thanks!

Regards,
Chris

**Comment by chrisfw** [comment]
Hi Markus,

This may take me some time to get to, but I will let you know when I have
had an opportunity to test it out.

Thanks,
Chris

**Comment by pacman82** [comment]
Hi Chris,

looking forward to it. This might become relevant for me, too.

Cheers, Markus

**Comment by chrisfw** [comment]
Hi Markus,

I confirmed that it works properly on Ubuntu with unixODBC 2.3.6 against
Oracle 19c with the 19c ODBC driver, so you can close out the issue.  Thank
you!

Regards.
Chris

**Comment by pacman82** [comment]
Hi Chris,

Thanks for the feedback. Closing the issue.

Cheers, Markus

**Comment by chrisfw** [comment]
No problem Markus!

Regards,
Chris

**Comment by chrisfw** [comment]
Thank you Markus for your quick response and all of the info you provided.  I will investigate on my end and let you know what I find out.

Regards,
Chris
