### ISSUE TITLE
Add flag to disable coloring

### ISSUE THREAD

**Issue by leo-schick** [pacman82/odbc2parquet#215]
Currently the CLI output is always colored which is nice, but sometimes looks a bit ugy when you see it through a console which doesn't support coloring (e.g. Jenkins). I would like to have a option to disable console coloring. Something similar to [terraform plan -no-color](https://github.com/hashicorp/terraform/issues/250)

**Comment by pacman82** [comment]
Just to be clear: You are referring to the color of the log output, are you?

Happy to introduce a `--no-color` flag. In the meanwhile defining the `NO_COLOR` environment variable should do the trick.

**Comment by leo-schick** [comment]
> Just to be clear: You are referring to the color of the log output, are you?

Yes. Thanks for the hint with env `NO_COLOR`!

**Comment by pacman82** [comment]
Version `0.9.1` with support for the `--no-color` flag has been released. Enjoy!
