### ISSUE TITLE
Getting the SQL statement from stdin

### ISSUE THREAD

**Issue by leo-schick** [pacman82/odbc2parquet#221]
I would like to have an option to pass the SQL statement to the `odbc2parquet query` command via stdin, via an extra option (e.g. `--query-from-stdin`) or by passing `-` as SQL query statement.

#### Option 1 by passing `-`
``` bash
cat my_sql_query.sql \
  | odbc2parquet query -c "<connection_string>" my-output.parquet -
```

#### Option 2 by using a new parameter `--query-from-stdin`
``` bash
cat my_sql_query.sql \
  | odbc2parquet query -c "<connection_string>" --query-from-stdin my-output.parquet
```

**Comment by pacman82** [comment]
Hello @leo-schick ,

could you help me understand your motivation for doing so? Would reading the query from a file also be an acceptable solution to your problem?

Cheers, Markus

**Comment by leo-schick** [comment]
I plan to extend the [Mara ETL framework](github.com/mara) with a db query to parquet function and would like to use odbc2parquet for this.

I’ll do this by extending the [mara_db.shell.copy_to_stdout_command](https://github.com/mara/mara-db/blob/main/mara_db/shell.py#L210-L234) function. See also https://github.com/mara/mara-db/issues/56

Mara is a nice ETL framework which does the data processing via shell tools instead of processing the data in python itself.  This gives an extra performance boost compared to other ETL engines relying on e.g. pandas or pyarrow

**Comment by pacman82** [comment]
> I’ll do this by extending the [mara_db.shell.copy_to_stdout_command](https://github.com/mara/mara-db/blob/main/mara_db/shell.py#L210-L234) function. See also https://github.com/mara/mara-db/issues/56

Just looking at this you may also like `odbcsv`.

**Comment by pacman82** [comment]
Hello @leo-schick ,

`odbc2parquet 0.9.4` accepts a query from standard in if you pass `-` as a query string.

Cheers, Markus
