### ISSUE TITLE
Is there a flag to split the parquet output by size?

### ISSUE THREAD

**Issue by samaguire** [pacman82/odbc2parquet#236]
as per the title

i.e. i want to output a large table, but have several parquet files generated, that are no bigger than 1GB

**Comment by pacman82** [comment]
Hello @samaguire,

Seems to me you are looking for the --file-size-threshold option of the query subcommand. See #190 , let me know if this solves your issue.

Cheers, Markus

**Comment by pacman82** [comment]
FYI: To learn more about `--file-size-threshold` or to see all options and flags for the `query` subcommand, you can execute `odbc2parquet query --help`.

**Comment by samaguire** [comment]
Ah. I thought it was odd to not have so ething like this. I didn't realize I could do the --help after query. 👍
