### ISSUE TITLE
Example PS Script

### ISSUE THREAD

**Issue by samaguire** [pacman82/odbc2parquet#24]
I recently wrote a Powershell script to extract some tables. Thought I would share a 'generic' version that extracts the tables from a localhost copy of the ContosoRetailDW db after pulling the latest version of the tool from github. It may be handy for others and I thought you could include in your ReadMe/Wiki.

[ContosoRetailDW_CreateParquetFiles.ps1.txt](https://github.com/pacman82/odbc2parquet/files/5786852/ContosoRetailDW_CreateParquetFiles.ps1.txt)

Grt Prj BTW!

**Comment by pacman82** [comment]
Hi, thanks for your kind words. I appreciate it. The script may indeed be useful to others. I am sadly at a loss currently what exactly to do with it. I've not done too much with powershell until now, and would have a hard time maintaining it and reviewing changes. I'll try to think of something. If you should decide to host in a repository of your own, I'd prominently link to it.

**Comment by samaguire** [comment]
👌 I've whipped up a repo for this with some instruction. <https://github.com/samaguire/odbc2parquet-PSscripts>

**Comment by pacman82** [comment]
Nice work! Mentioned your repository in the Readme.

**Comment by samaguire** [comment]
👍
