### ISSUE TITLE
Warnings shown when quiet flag 

### ISSUE THREAD

**Issue by SDKongstad** [pacman82/odbc2parquet#257]
I am mostly running odbc2parquet from Powershell. 
I noticed that I always get warnings when running - which powershell interprets as errors. To fix this I tried using the -q flag.
However warnings are still shown
![image](https://user-images.githubusercontent.com/33683982/190603636-8be59384-dbc9-4381-828e-eb48b2095ac3.png)

Is it possible to introduce a flag so only errors are displayed?

**Comment by pacman82** [comment]
Thanks for reporting this. Seems `odbc2parquet` had a bug which caused verbosity always be one level too high. `odbc2parquet 0.13.1` is released just now. Update to it, and `--quite` should work as intended.

**Comment by pacman82** [comment]
Does it work for you now? I use powershell myself if on windows and did not experience trouble before, so I am curious if a different issue emerges from this one.

**Comment by pacman82** [comment]
Thanks for your reply!

Cheers, Markus
