### ISSUE TITLE
Compression SNAPPY not possible since version 0.13.2

### ISSUE THREAD

**Issue by leo-schick** [pacman82/odbc2parquet#286]
When I create a parquet file with compression snappy the compression is ZSTD even I defined it with `--column-compression-default snappy`.

This seems to be a bug with a new version because in version 0.8.0 this worked, but with version 0.13.2 this does not work anymore.

**Comment by leo-schick** [comment]
I did now a bit testing with the different versions and I could only reproduce this error with the latest version 0.13.2. When I choose version 0.13.1 and below it works out fine.

**Comment by pacman82** [comment]
Thanks again for reporting this behaviour. Still preoccupied investigating the converted type of timestamps. I guess this is due to an update in an upstream version. Either parquet or clap. I'll investigate.

**Comment by leo-schick** [comment]
Yea 👍 I was guessing the same. No pressure from my side. For me the timestamp issues are more important than this.

**Comment by pacman82** [comment]
That seems to have been just a really dumb typo on my side than I migrated to the newest `clap` version.

**Comment by pacman82** [comment]
Released `odbc2parquet 0.13.3` which fixes the behaviour.
