### ISSUE TITLE
Parquet format version support

### ISSUE THREAD

**Issue by ErikJansenIRefact** [pacman82/odbc2parquet#423]
Hi,

The parquet file is written in Parquet version 1.0 format.
Is support for writing other Parquet format versions possible? For example Parquet version 2.6 supports nanosecond time precision.

**Comment by pacman82** [comment]
note to self: <https://docs.rs/parquet/latest/parquet/file/properties/enum.WriterVersion.html>

**Comment by pacman82** [comment]
Hello @ErikJansenIRefact ,

In the meanwhile to versions of `odbc2parquet` have been released. Since `odbc2parquet 1.0.0` parquet files are written in the parquet 2.0 format. The newest release `odbc2parquet 2.0.0` writes timestamps as nano seconds provided the precision of the timestamp in the database is greater than or equal to seven.

This should take care of this issue. I would be happy if you could confirm.

Best, Markus

**Comment by ErikJansenIRefact** [comment]
Update!

Checked the parquet docs. A nanosecond precision timestamp has limitations:

_Due to the range of the int64 type, timestamps using the NANOS unit can only represent values between 1677-09-21 00:12:43 and 2262-04-11 23:47:16. Values outside of this range can not be represented with the NANOS unit. (Other precisions have similar limits but those are outside of the domain for practical everyday usage.)_

So either you need to down cast a datetime2(7) to a datetime2(6) (in the query or database storage) or the odbc2parquet utility should execute this downcast.

What do you think?

**Comment by pacman82** [comment]
With regards to the domain, an argument could be made if you make statements about centuries in the future, you likely do not have nanoseconds precision. In terms of `odbc2parquet` I am torn between clamping the values between min/max or just throwing an error.

**Comment by pacman82** [comment]
My current opinion for both `odbc2parquet` and `arrow-odbc` is to highlight the domain error to the user and throw an error. The user can then make a decision based on his domain how to treat values which do not map into arrow/parquet. One way to do so, you already suggested by casting it into datetime2(6) instead.

Best, Markus

**Comment by ErikJansenIRefact** [comment]
I agree. The question is if you can handle these errors? As long as a date time value with nanosecond precision is within the boundaries it works as expected. So only throw if the value is out of the range.

**Comment by pacman82** [comment]
yeah, sure. If the timestamps are not out of range, they will should be written correctly

**Comment by pacman82** [comment]
`odbc2parquet 2.0.1` has been released. It raises an error if timestamps with nano precision are out of range.
