### ISSUE TITLE
Feature suggestion: connect to URL  `postgresql://username:pass@host/database`

### ISSUE THREAD

**Issue by SamuelMarks** [pacman82/odbc2parquet#434]
Possible with an explicit driver specification, e.g., using the `drivername+postgresql` syntax popular in SQLalchemy

**Comment by pacman82** [comment]
How to connect to databases is specified in the ODBC standard itself. It offers 3 possibilities:

* Connection String
* DNS name
* Prompt (windows only)

I do not intend to add or remove from it. SQLalchemy is a very different thing. It has special modules for databases it supports. I would prefer to stay away from that and rely fully on the ODBC drivers of the different data sources.

Best, Markus
