### ISSUE TITLE
--no-empty-file option doesn't work properly when row-groups-per-file should devide result into few files 

### ISSUE THREAD

**Issue by Rickitik** [pacman82/odbc2parquet#477]
When i try to use --no-empty-file option in such way :
`odbc2parquet query --batch-size-memory 500Mb  --row-groups-per-file 20  --no-empty-file ........` from empty table

first file with _01.par is produced and  stderror contains raised Error "No such file" . So when procedure finished i have an error and a file in my directory.

**Comment by pacman82** [comment]
I am not sure I fully understand. Could you provide the complete command line and output to standard error? Feel free to xxx out table names.

Especially I would like to understand there the "No such file" error could stem from.

Best, Markus

**Comment by Rickitik** [comment]
Query:
`odbc2parquet query --batch-size-memory 300Mb --column-compression-default zstd --row-groups-per-file 20 --no-empty-file --connection-string "Driver=Some connection string" "/code/data/processed/test_file_from_server.par" "SELECT  * FROM XXXXXX"`

Table in db is empty. 

Output is:
![Screenshot_1](https://github.com/pacman82/odbc2parquet/assets/61269044/9cef44eb-6866-4664-8076-11a7f8b06a4b)

Produced file in directory:
![Screenshot_2](https://github.com/pacman82/odbc2parquet/assets/61269044/aa7cdad3-b629-4bad-a87c-3e402d174cae)

**Comment by pacman82** [comment]
I am interested in the  "No such file" error. What database do you use?

**Comment by Rickitik** [comment]
SQL server DB

**Comment by Rickitik** [comment]
if it can help i made the same query with debug logging level
![Screenshot_4](https://github.com/pacman82/odbc2parquet/assets/61269044/11b56f44-20b3-4ee5-ad3e-fb30db16b2e2)

**Comment by pacman82** [comment]
`odbc2parquet 3.0.1` is released with a fix
