### ISSUE TITLE
Data source must return valid UTF16 in wide character buffer: Utf16Error

### ISSUE THREAD

**Issue by marleybacelar** [pacman82/odbc2parquet#484]
While exporting data from MS SQL server, I am getting the following error:

**1m'main' panicked at 'Data source must return valid UTF16 in wide character buffer: Utf16Error**

**Comment by pacman82** [comment]
Could you narrow in what column in your query is causing it? Could you run `odbc2parquet` with higher levels of verbosity (`-vvv`) and share the log output?

**Comment by pacman82** [comment]
`odbc2parquet 3.1.1` has been released. It will no longer panic, but emit a proper error to standard out. The error should will also contain the name of the column causing the issue. If you could reproduce the error with the new version and share the log output, we may learn enough, for me to reproduce the issue.

Best, Markus

**Comment by marleybacelar** [comment]
Thanks Marcus, I changed the --enconding from Auto to System, and worked well, will go back and check with the -vvv option.

**Comment by pacman82** [comment]
Closing this as I do not know how to act on this. The better error message has to suffice for now.
