### ISSUE TITLE
Linking with 'cc' failed exit code: 1 SOLVED

### ISSUE THREAD

**Issue by gustavo-avalos-villasenor** [pacman82/odbc2parquet#53]
Thanks, Markus, "Linking with 'cc' failed exit code: 1" was solved as you told me.

To make it work over Ubuntu:
$sudo apt install unixodbc-dev

![image](https://user-images.githubusercontent.com/50249671/115542870-04dda100-a2a1-11eb-9e13-ccec923fb87d.png)

**Comment by pacman82** [comment]
I should update the readme to list unixodbc as an explicit requirement for linux users. Thanks for the issue.
