### ISSUE TITLE
Virus warning in latest release (6.1.1)?

### ISSUE THREAD

**Issue by fdcastel** [pacman82/odbc2parquet#642]
The latest release at

https://github.com/pacman82/odbc2parquet/releases/tag/v6.1.1

- Google Chrome does not permit downloading it.
- Microsoft Defender provides additional details:

    ```
    Trojan:Script/Wacatac.B!ml
    Details: This program is dangerous and executes commands from an attacker.
    ```

**Comment by pacman82** [comment]
Well, it is not a trojan. Yet you really should not trust the author of an artifact with such statements ;-)

Seriously though, there are not any CVEs reported for any of `odbc2parquet`s dependencies. This is most likely a false positive. It is also not uncommon for browsers to disallow downloading any executable from the internet.

**Comment by pacman82** [comment]
I have no idea how to act on this further. Closing the issue. If there is something concrete I could do to smooth installation please reopen or create a new issue.
