### ISSUE TITLE
Is there a way to access to the command from any user

### ISSUE THREAD

**Issue by gustavo-avalos-villasenor** [pacman82/odbc2parquet#68]
Hi, I installed odbc2parquet as root and it works ok, but I'm not able to run it from other users. Is there a way to do it?

Thank you, Markus!

**Comment by pacman82** [comment]
Yeah, there are lots of ways. As long as the executable is in a path accessible by the user and in the `PATH` environment variable it will work. If the cargo toolchain is installed for the user you want it to execute as you can just run

Are you running on Linux or OS-X? These ideas should work on both platforms:

* `cargo install odbc2parquet` for that user.
* Just copy the executable to `${HOME}/bin`, there ${HOME} is the home directory of the user. You may need to change file permissions with `chmod`.
* copy the executable to `/usr/local/bin`

All of this is not specific to this tool. If you have someone familiar with the platform you are working on he / she should be able to help you without problems. `cargo install` command installs into `${HOME}/.cargo/bin` by default, if you are looking for the current place of the tool. So on linux you would find the `odbc2parquet` executable in `/root/.cargo/bin/odbc2parquet`.

Cheers, Markus

**Comment by pacman82** [comment]
@gustavo-avalos-villasenor Has the answer been helpful enough, to enable you to install it for all users, or are you still stuck?

**Comment by gustavo-avalos-villasenor** [comment]
Thank you very much Markus it works!!! You save my life, many thanks!

**Comment by pacman82** [comment]
You are welcome!
